export const ROLES_CONFIG = {
  admin: {
    id: 'admin',
    roleKey: 'ADMIN',
    label: 'Admin',
    badge: 'Admin Portal',
    title: 'System Administrator Access',
    description: 'Full administrative access and institutional system management',
    inputLabel: 'Admin Email / ID',
    placeholder: 'admin@sms.com',
    demoUsername: 'admin@sms.com',
    demoPassword: 'Admin@12345',
    demoPhone: '+1 (555) 942-8821',
    themeColor: {
      primary: 'bg-indigo-600',
      hover: 'hover:bg-indigo-700',
      gradient: 'from-indigo-600 to-blue-600',
      subtle: 'bg-indigo-50/70 dark:bg-indigo-950/40',
      border: 'border-indigo-100 dark:border-indigo-900/50',
      text: 'text-indigo-600 dark:text-indigo-400',
      accent: '#4f46e5',
    },
  },
  student: {
    id: 'student',
    roleKey: 'STUDENT',
    label: 'Student',
    badge: 'Student Portal',
    title: 'Student Learning Workspace',
    description: 'Access attendance, live courses, assignments & exam grades',
    inputLabel: 'Student Roll No / Email',
    placeholder: 'CS202401 or student1@sms.com',
    demoUsername: 'CS202401',
    demoPassword: 'Student@12345',
    demoPhone: '+1 (555) 234-5678',
    themeColor: {
      primary: 'bg-sky-500',
      hover: 'hover:bg-sky-600',
      gradient: 'from-sky-500 to-blue-600',
      subtle: 'bg-sky-50/70 dark:bg-sky-950/40',
      border: 'border-sky-100 dark:border-sky-900/50',
      text: 'text-sky-600 dark:text-sky-400',
      accent: '#0ea5e9',
    },
  },
  parent: {
    id: 'parent',
    roleKey: 'PARENT',
    label: 'Parent',
    badge: 'Parent Portal',
    title: 'Guardian & Parent Center',
    description: 'Monitor child performance, fee dues, attendance & teacher notices',
    inputLabel: 'Parent Registered Email',
    placeholder: 'parent1@sms.com',
    demoUsername: 'parent1@sms.com',
    demoPassword: 'Parent@12345',
    demoPhone: '+1 (555) 876-5432',
    themeColor: {
      primary: 'bg-teal-600',
      hover: 'hover:bg-teal-700',
      gradient: 'from-teal-600 to-sky-600',
      subtle: 'bg-teal-50/70 dark:bg-teal-950/40',
      border: 'border-teal-100 dark:border-teal-900/50',
      text: 'text-teal-600 dark:text-teal-400',
      accent: '#0d9488',
    },
  },
};
