"""add_branches_and_sections

Revision ID: d28c247b6d25
Revises: d890443355e4
Create Date: 2026-10-05 12:04:34.996996

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd28c247b6d25'
down_revision: Union[str, Sequence[str], None] = 'd890443355e4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('branches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('hod_name', sa.String(length=100), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('intake_capacity', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('branches', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_branches_code'), ['code'], unique=True)
        batch_op.create_index(batch_op.f('ix_branches_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_branches_name'), ['name'], unique=True)

    op.create_table('sections',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('class_id', sa.Integer(), nullable=False),
    sa.Column('branch_id', sa.Integer(), nullable=True),
    sa.Column('room_number', sa.String(length=50), nullable=True),
    sa.Column('capacity', sa.Integer(), nullable=False),
    sa.Column('class_teacher', sa.String(length=100), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['class_id'], ['classes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('sections', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sections_branch_id'), ['branch_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_sections_class_id'), ['class_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_sections_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_sections_name'), ['name'], unique=False)

    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.add_column(sa.Column('branch_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('section_id', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_students_branch_id'), ['branch_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_students_section_id'), ['section_id'], unique=False)
        batch_op.create_foreign_key('fk_students_branch_id', 'branches', ['branch_id'], ['id'], ondelete='SET NULL')
        batch_op.create_foreign_key('fk_students_section_id', 'sections', ['section_id'], ['id'], ondelete='SET NULL')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.drop_constraint('fk_students_section_id', type_='foreignkey')
        batch_op.drop_constraint('fk_students_branch_id', type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_students_section_id'))
        batch_op.drop_index(batch_op.f('ix_students_branch_id'))
        batch_op.drop_column('section_id')
        batch_op.drop_column('branch_id')

    with op.batch_alter_table('sections', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sections_name'))
        batch_op.drop_index(batch_op.f('ix_sections_id'))
        batch_op.drop_index(batch_op.f('ix_sections_class_id'))
        batch_op.drop_index(batch_op.f('ix_sections_branch_id'))

    op.drop_table('sections')
    with op.batch_alter_table('branches', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_branches_name'))
        batch_op.drop_index(batch_op.f('ix_branches_id'))
        batch_op.drop_index(batch_op.f('ix_branches_code'))

    op.drop_table('branches')
    # ### end Alembic commands ###
