"""create_function_tracker_tables

Revision ID: d890443355e4
Revises: 3a226bae9123
Create Date: 2026-10-05 11:11:20.094126

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd890443355e4'
down_revision: Union[str, Sequence[str], None] = '3a226bae9123'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('app_functions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('display_name', sa.String(length=150), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('endpoint', sa.String(length=255), nullable=True),
    sa.Column('http_method', sa.String(length=10), nullable=True),
    sa.Column('module', sa.String(length=150), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('total_executions', sa.Integer(), nullable=False),
    sa.Column('successful_executions', sa.Integer(), nullable=False),
    sa.Column('failed_executions', sa.Integer(), nullable=False),
    sa.Column('avg_latency_ms', sa.Float(), nullable=False),
    sa.Column('last_executed_at', sa.DateTime(), nullable=True),
    sa.Column('last_execution_status', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('app_functions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_app_functions_category'), ['category'], unique=False)
        batch_op.create_index(batch_op.f('ix_app_functions_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_app_functions_name'), ['name'], unique=True)

    op.create_table('function_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('function_id', sa.Integer(), nullable=True),
    sa.Column('function_name', sa.String(length=100), nullable=False),
    sa.Column('endpoint', sa.String(length=255), nullable=True),
    sa.Column('http_method', sa.String(length=10), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('user_role', sa.String(length=20), nullable=True),
    sa.Column('user_identifier', sa.String(length=100), nullable=True),
    sa.Column('status_code', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('execution_duration_ms', sa.Float(), nullable=False),
    sa.Column('ip_address', sa.String(length=50), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('executed_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['function_id'], ['app_functions.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('function_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_function_logs_executed_at'), ['executed_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_function_logs_function_id'), ['function_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_function_logs_function_name'), ['function_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_function_logs_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_function_logs_status'), ['status'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('function_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_function_logs_status'))
        batch_op.drop_index(batch_op.f('ix_function_logs_id'))
        batch_op.drop_index(batch_op.f('ix_function_logs_function_name'))
        batch_op.drop_index(batch_op.f('ix_function_logs_function_id'))
        batch_op.drop_index(batch_op.f('ix_function_logs_executed_at'))

    op.drop_table('function_logs')
    with op.batch_alter_table('app_functions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_app_functions_name'))
        batch_op.drop_index(batch_op.f('ix_app_functions_id'))
        batch_op.drop_index(batch_op.f('ix_app_functions_category'))

    op.drop_table('app_functions')
    # ### end Alembic commands ###
